require 'json'

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SignalfoxReactNativeExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    hermesc_path = File.expand_path('../node_modules/hermes-compiler/hermesc/osx-bin/hermesc', __dir__)

    Dir.glob(File.join(__dir__, 'Pods/Target Support Files/Pods-SignalfoxReactNativeExample/*.xcconfig')).each do |xcconfig_path|
      xcconfig = File.read(xcconfig_path)
      updated = xcconfig.gsub(/^HERMES_CLI_PATH = .*$/, "HERMES_CLI_PATH = #{hermesc_path}")
      File.write(xcconfig_path, updated) if updated != xcconfig
    end

    hermes_podspec_path = File.join(__dir__, 'Pods/Local Podspecs/hermes-engine.podspec.json')
    if File.exist?(hermes_podspec_path)
      hermes_podspec = JSON.parse(File.read(hermes_podspec_path))
      hermes_podspec['user_target_xcconfig'] ||= {}
      hermes_podspec['user_target_xcconfig']['HERMES_CLI_PATH'] = hermesc_path
      File.write(hermes_podspec_path, JSON.pretty_generate(hermes_podspec))
    end
  end
end
